export const allCombatSituationUnits = [
    {id: 1001,
        x: -4,
        y: -3,
        was: {x: -4, y: -2},
        d: 0,
        power: 5,
        deleted: false},
    {id: 1002,
        x: -3,
        y: -2,
        was: {x: -3, y: -1},
        d: 0,
        power: 5,
        deleted: false},
    {id: 1003,
        x: -4,
        y: 3,
        was: {x: -4, y: 3},
        d: 1,
        power: 5,
        deleted: false},
    {id: 1004,
        x: 3,
        y: 3,
        was: {x: 2, y: 3},
        d: 1,
        power: 2,
        deleted: false},
    {id: 1005,
        x: 4,
        y: 2,
        was: {x: 4, y: 1},
        d: 2,
        power: 2,
        deleted: false},
    {id: 1006,
        x: 2,
        y: 4,
        was: {x: 2, y: 4},
        d: 0,
        power: 2,
        deleted: false},
    {id: 1007,
        x: 2,
        y: 2,
        was: {x: 2, y: 1},
        d: 2,
        power: 2,
        deleted: false},
    {id: 1008,
        x: 3,
        y: -4,
        was: {x: 3, y: -4},
        d: 2,
        power: 2,
        deleted: false},
    {id: 1009,
        x: 3,
        y: -2,
        was: {x: 3, y: -1},
        d: 0,
        power: 2,
        deleted: false},
    {id: 1010,
        x: 2,
        y: -3,
        was: {x: 1, y: -3},
        d: 1,
        power: 2,
        deleted: false},
    {id: 1011,
        x: 0,
        y: -3,
        was: {x: -1, y: -3},
        d: 1,
        power: 4,
        deleted: false},
    {id: 1012,
        x: 1,
        y: -2,
        was: {x: 1, y: -1},
        d: 0,
        power: 4,
        deleted: false},
    {id: 1013,
        x: -2,
        y: -4,
        was: {x: -2, y: -4},
        d: 2,
        power: 1,
        deleted: false},
    {id: 1014,
        x: -2,
        y: -3,
        was: {x: -2, y: -3},
        d: 0,
        power: 2,
        deleted: false},
    {id: 1015,
        x: -4,
        y: -1,
        was: {x: -4, y: -1},
        d: 2,
        power: 10,
        deleted: false},
    {id: 1016,
        x: -2,
        y: 1,
        was: {x: -2, y: 1},
        d: 0,
        power: 8,
        deleted: false},
    {id: 1017,
        x: -1,
        y: -4,
        was: {x: -1, y: -4},
        d: -1,
        power: 30,
        deleted: false},
    {id: 1018,
        x: -1,
        y: -3,
        was: {x: -1, y: -2},
        d: 0,
        power: 10,
        deleted: false},

];
export const allCombatSituationEnemies = [
    {id: 1001,
        x: -4,
        y: -4,
        was: {x: -4, y: -4},
        d: 2,
        power: 5,
        deleted: false},
    {id: 1002,
        x: -3,
        y: -4,
        was: {x: -3, y: -4},
        d: 2,
        power: 5,
        deleted: false},
    {id: 1003,
        x: -3,
        y: 4,
        was: {x: -3, y: 4},
        d: 0,
        power: 5,
        deleted: false},
    {id: 1004,
        x: 4,
        y: 4,
        was: {x: 4, y: 4},
        d: 0,
        power: 5,
        deleted: false},
    {id: 1005,
        x: 2,
        y: 3,
        was: {x: 2, y: 4},
        d: 0,
        power: 5,
        deleted: false},
    {id: 1006,
        x: 3,
        y: -3,
        was: {x: 3, y: -4},
        d: 2,
        power: 3,
        deleted: false},
    {id: 1007,
        x: 4,
        y: -3,
        was: {x: 4, y: -3},
        d: 3,
        power: 4,
        deleted: false},
    {id: 1008,
        x: 2,
        y: -3,
        was: {x: 3, y: -3},
        d: 3,
        power: 4,
        deleted: false},
    {id: 1009,
        x: 1,
        y: -4,
        was: {x: 1, y: -4},
        d: 2,
        power: 4,
        deleted: false},
    {id: 1010,
        x: -3,
        y: -1,
        was: {x: -3, y: -1},
        d: 2,
        power: 10,
        deleted: false},
    {id: 1011,
        x: -2,
        y: -1,
        was: {x: -2, y: -1},
        d: 2,
        power: 10,
        deleted: false},
    {id: 1012,
        x: 0,
        y: -1,
        was: {x: 0, y: -1},
        d: 2,
        power: 100,
        deleted: false},
];

export const allCombatSituationBonuses = [
    {id: 1000,
        x: -4,
        y: 0,
        power: -8,
        deleted: false},
    {id: 1001,
        x: -3,
        y: 0,
        power: 8,
        deleted: false},
    {id: 1002,
        x: -2,
        y: 0,
        power: -8,
        deleted: false},
];
